version: "3.9"

networks:
  default:
    name: proxy-tier

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-n8n}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-S3gur0!@#Admin}
      POSTGRES_DB: ${POSTGRES_DB:-n8n}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - ./data/redis:/data

  evolution:
    image: atendai/evolution-api:latest
    container_name: evolution
    restart: always
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080
      # - NODE_ENV=${EVOLUTION_NODE_ENV:-production}
      # - DB_TYPE=postgres
      # - DB_HOST=postgres
      # - DB_PORT=5432
      # - DB_USER=${POSTGRES_USER:-n8n}
      # - DB_PASS=${POSTGRES_PASSWORD:-S3gur0!@#Admin}
      # - DB_NAME=${POSTGRES_DB:-n8n}
    volumes:
      - ./data/evolution:/app/storage

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "80:80"
      - "81:81" # painel de administração
      - "443:443"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data/npm:/data
      - ./data/letsencrypt:/etc/letsencrypt
