version: "3.9"

networks:
  default:
    name: proxy-tier

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-n8n}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-S3gur0!@#Admin}
      POSTGRES_DB: ${POSTGRES_DB:-n8n}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - ./data/redis:/data

  n8n:
    image: n8nio/n8n:1.19.4
    container_name: n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${POSTGRES_HOST:-postgres}
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB:-n8n}
      - DB_POSTGRESDB_USER=${POSTGRES_USER:-n8n}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD:-n8npass}
      - N8N_REDIS_HOST=redis
      - N8N_REDIS_PORT=6379
      - N8N_HOST=n8n.tsswebapps.com
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER:-admin}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD:-suasenha123}
    depends_on:
      - postgres
      - redis
    volumes:
      - ./data/n8n:/home/node/.n8n

  evolution:
    image: atendai/evolution-api:latest
    container_name: evolution
    restart: always
    environment:
      - SERVER_PORT=8080
      - NODE_ENV=${EVOLUTION_NODE_ENV:-production}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY:-huF8Dt7m5o90d0obeRglCFPOOlJlPLQ4cCymWA7dTRWcGoO3fBI6ZYvhfp1AS2sF}
    volumes:
      - ./data/evolution:/app/storage

  # npm:
  #   image: jc21/nginx-proxy-manager:latest
  #   container_name: nginx-proxy-manager
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "81:81" # painel de administração
  #     - "443:443"
  #   environment:
  #     DB_SQLITE_FILE: "/data/database.sqlite"
  #   volumes:
  #     - ./data/npm:/data
  #     - ./data/letsencrypt:/etc/letsencrypt
